/* ── Comments ── */
/* SAS showcase: warehouse inventory reporting.
   TODO: read from the warehouse database. FIXME: missing-value handling. */
* A statement comment ends at the semicolon;
*
   A multi-line statement comment;
%* A macro comment is not sent to the log;
/*
   Block comment with * and ; inside
*/

/* ── Options, titles, libraries ── */
options nodate nonumber linesize=120 pagesize=60 mprint symbolgen mlogic compress=yes;
options validvarname=v7 fullstimer msglevel=i;
title1 "Warehouse Inventory Report";
title2 j=l "Left-justified" j=r "Right-justified";
footnote1 'Generated by the nightly job';
libname inv "/data/inventory" access=readonly;
libname work2 base "/tmp/work" ;
filename src "/data/inventory/orders.csv" encoding="utf-8";
filename out temp;
ods graphics on / width=6in height=4in;
ods html file="report.html" style=journal;
ods pdf file="report.pdf";
ods listing close;

/* ── Macro variables ── */
%let reorder_point = 25;
%let warehouse = north;
%let today = %sysfunc(today(), yymmdd10.);
%let name_with_amp = AT&T;
%let quoted = %str(a;b);
%let nrstr = %nrstr(&notexpanded %notmacro);
%global status_code;
%local i total;
%put NOTE: reorder point is &reorder_point and warehouse &warehouse..;
%put _user_;
%symdel total;

/* ── DATA step ── */
data orders(keep=number total status paid placed_at label) work.low_stock / view=work.low_stock;
    length status $12 label $40 sku $10;
    format placed_at date9. total dollar12.2 stamp datetime20.;
    informat placed_at yymmdd10.;
    retain running 0 flag 'N';
    array amounts{3} a1-a3 (1 2 3);
    array names{*} $ n1-n5;
    infile datalines dlm=',' dsd missover firstobs=1 obs=max truncover;
    input number total status $ placed_at :yymmdd10. @;
    input @1 sku $char10. @12 qty 5. +2 price comma8.2 / extra $ #3 more $;
    paid = (status = 'paid');
    if total >= 100 then label = "large";
    else if total > 0 then label = 'small';
    else label = "none";
    if missing(total) or total < 0 and status ne 'cancelled' then delete;
    where total > 0 and status in ('paid', 'pending') and placed_at between '01JAN2026'd and '31DEC2026'd;
    by status;
    if first.status then running = 0;
    running + total;
    if last.status then output;
    select (status);
        when ('paid') flag = 'Y';
        when ('pending', 'open') flag = 'P';
        otherwise flag = 'N';
    end;
    do i = 1 to 3;
        amounts{i} = amounts{i} * 2;
    end;
    do j = 10 to 1 by -2 while (j > 4);
    end;
    do until (k >= 3);
        k + 1;
    end;
    do k = 1, 3, 5;
    end;
    total = round(total * 1.075, 0.01);
    stamp = datetime();
    date = mdy(9, 24, 2026);
    text = cats('Order ', put(number, z5.), ' ', strip(status));
    pos = index(label, 'rg') + find(label, 'a', 'i') + prxmatch('/^\d+$/', '123');
    call missing(of n1-n5);
    call symputx('last_status', status);
    if _n_ = 1 then put 'first row' _all_;
    if eof then stop;
    return;
    link done;
    done: put 'done';
    goto finish;
    finish:;
    abort;
    output work.low_stock;
    drop temp_var;
    rename old_name=new_name;
    modify;
    set inv.orders(where=(status = 'paid') rename=(a=b)) end=eof nobs=n point=ptr;
    merge orders(in=a) inv.customers(in=b);
    update master transactions;
    if a and not b;
    declare hash h(dataset: 'work.lookup');
    h.defineKey('sku');
    h.defineData('price');
    h.defineDone();
    rc = h.find();
    datalines;
1,120.50,paid,2026-09-24
2,42,pending,2026-09-25
3,0,cancelled,2026-09-26
4,88.25,paid,2026-09-27
;
run;

data _null_;
    file print;
    file out;
    put "Total orders: " _n_ 5. / "second line" @40 "col 40";
    put (a b c) (3. 4.2 $5.);
run;

data cards_example;
    input x y;
    cards4;
1 2
3 4
;;;;
run;

/* ── PROC steps ── */
proc sql noprint;
    create table by_status as
    select status, count(*) as n, sum(total) as revenue format=comma10.2 label='Revenue',
           avg(total) as mean_total, max(total) as largest
    from orders as o left join inv.customers as c on o.cust_id = c.id
    where o.total > &reorder_point and status like 'p%' and number in (select number from work.low_stock)
    group by status
    having calculated revenue > 0
    order by revenue desc, status asc;

    select count(*) into :n_rows trimmed from by_status;
    select distinct status into :statuses separated by ',' from orders;
    insert into orders (number, total) values (5, 12.5) values (6, 0);
    update orders set total = total * 1.1 where status = 'paid';
    delete from orders where total = 0;
    alter table orders add region char(8);
    drop table work.scratch;
    describe table orders;
    create index status on orders(status);
    create view v_paid as select * from orders where paid = 1;
    select case when total > 100 then 'high' when total > 10 then 'mid' else 'low' end as band from orders;
    select a.*, b.name from a inner join b on a.id = b.id union all select * from c except select * from d;
quit;

proc sort data=orders out=sorted nodupkey; by descending total status; run;

proc means data=orders n mean max min std sum maxdec=2 noprint;
    class status;
    where paid;
    var total;
    output out=stats mean=avg_total sum=sum_total / autoname;
run;

proc freq data=orders;
    tables status * paid / chisq nocol norow nopercent out=freqs;
run;

proc print data=sorted(obs=10) noobs label;
    var number total status;
    format total dollar10.2;
    sum total;
run;

proc report data=orders nowd headline;
    column status total n;
    define status / group "Status";
    define total / analysis sum format=dollar12.2;
    define n / "Count";
    break after status / summarize;
    compute after;
        status = 'All';
    endcomp;
run;

proc sgplot data=orders;
    vbar status / response=total stat=sum datalabel;
    xaxis label="Status";
    yaxis grid values=(0 to 500 by 100);
run;

proc format;
    value $statusfmt 'paid' = 'Paid' 'pending' = 'Open' other = 'Unknown';
    value totalfmt low-<10 = 'Small' 10-<100 = 'Medium' 100-high = 'Large';
    picture usd low-high = '000,009.99' (prefix='$');
    invalue statusin 'P' = 1 'N' = 0;
run;

proc reg data=orders; model total = number / selection=stepwise; quit;
proc logistic data=orders descending; class status; model paid = total; run;
proc import datafile=src out=imported dbms=csv replace; getnames=yes; guessingrows=max; run;
proc export data=orders outfile=out dbms=csv replace; run;
proc transpose data=stats out=wide prefix=m_; id status; var avg_total; run;
proc datasets library=work nolist; delete scratch; modify orders; index create number; quit;
proc contents data=orders varnum; run;
proc tabulate data=orders; class status; var total; table status, total*(n sum mean); run;
proc univariate data=orders; var total; histogram total / normal; run;
proc compare base=orders compare=sorted; run;
proc copy in=work out=inv; select orders; run;
proc iml; x = {1 2, 3 4}; print (x * x`); quit;

/* ── Macro language ── */
%macro report(ds, title=, top=10);
    %local rows;
    %if %length(&title) = 0 %then %let title = Report for &ds;
    title "&title";
    %if &top > 0 %then %do;
        proc print data=&ds(obs=&top) noobs; run;
    %end;
    %else %if &top = 0 %then %do;
        %put WARNING: nothing to print;
    %end;
    %else %do;
        %put ERROR: negative top;
        %return;
    %end;
    %do i = 1 %to 3;
        %put iteration &i;
    %end;
    %do %while (&i < 5);
        %let i = %eval(&i + 1);
    %end;
    %do %until (&i >= 7);
        %let i = %eval(&i + 1);
    %end;
    %let upper = %upcase(&title);
    %let sub = %substr(&title, 1, 3);
    %let scan = %scan(a b c, 2);
    %let calc = %sysevalf(1.5 * 2);
    %let exists = %sysfunc(exist(work.orders));
    %let quoted = %bquote(it's);
    %let unq = %unquote(&quoted);
    %let q = %qsysfunc(compress(a b));
    %let idx = %index(&title, port);
    %let cnt = %sysfunc(countw(&title));
    %goto exit;
    %exit: %mend report;

%report(by_status, title=Revenue by status)
%report(ds=orders, top=0)

%macro loop_over(list);
    %let n = %sysfunc(countw(&list));
    %do k = 1 %to &n;
        %let item = %scan(&list, &k);
        %put &=item;
    %end;
%mend;
%loop_over(a b c)

%macro fn(x) / store source des="stored macro";
    %eval(&x * 2)
%mend fn;

%include "helpers.sas" / source2;
%include src;
%let rc = %sysfunc(dosubl(%nrstr(data _null_; run;)));
%sysexec echo hello;
%sysrput var=1;
%abort cancel;
%inc "other.sas";

/* ── Missing values and special literals ── */
data literals;
    a = .;
    b = .A;
    c = ._;
    d = 1.5e3;
    e = 1E-3;
    f = 0x1F;
    g = 'it''s single';
    h = "double ""quoted"" text";
    i = '01JAN2026'd;
    j = '12:30:00't;
    k = '01JAN2026:12:30:00'dt;
    l = 'ff'x;
    m = '1010'b;
    n = "name with space"n;
    o = 'hello'n;
    p = 5 ** 2 || 'a' !! 'b';
    q = (a = 1) + (a ne 2) + (a ^= 3) + (a ~= 4) + (a < 5) + (a <= 6) + (a > 7) + (a >= 8);
    r = a in (1, 2, 3) and not b or c;
    s = a eq 1 and b gt 2 or c lt 3 and d ge 4 or e le 5;
    t = min(1, 2) <> 3 >< 4;
    u = -a + +b * c / d;
    v = a || b || c;
run;

ods html close;
ods pdf close;
ods listing;
endsas;
