[global]
   workgroup = WORKGROUP
   server string = Inventory file server
   security = user
   map to guest = Bad User

[shares]
   path = /srv/shares
   read only = no
   browseable = yes
   valid users = @staff
